backend:
  name: github
  repo: micho9879/demo-strony
  branch: main

media_folder: "img"
public_folder: "/img"

media_libraries:
  all:
    transformations:
      raster_image:
        format: webp
        width: 1920
        quality: 85

collections:
  - name: "podesty"
    label: "Podesty Ruchome"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/podesty.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/podesty_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/podesty_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "suwnice"
    label: "Suwnice"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/suwnice.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/suwnice_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/suwnice_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "wozki-podnosnikowe"
    label: "Wózki Widłowe Podnośnikowe"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/wozki-podnosnikowe.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/wozki-podnosnikowe_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/wozki-podnosnikowe_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "wozki-specjalizowane"
    label: "Wózki Widłowe Specjalizowane"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/wozki-specjalizowane.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/wozki-specjalizowane_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/wozki-specjalizowane_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "zurawie-przenosne"
    label: "Żurawie Przenośne"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/zurawie-przenosne.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/zurawie-przenosne_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/zurawie-przenosne_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "zurawie-samojezdne"
    label: "Żurawie Samojezdne"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/zurawie-samojezdne.json"
        fields:
          - label: "Pytania UDT"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/zurawie-samojezdne_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/zurawie-samojezdne_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}

  - name: "bhp"
    label: "Szkolenie BHP"
    files:
      - label: "Pytania Egzaminacyjne"
        name: "exam"
        file: "data/bhp.json"
        fields:
          - label: "Pytania BHP"
            name: "questions"
            widget: "list"
            fields:
              - {label: "ID pytania", name: "id", widget: "number"}
              - {label: "Treść pytania", name: "question", widget: "string"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
              - label: "Opcje odpowiedzi"
                name: "options"
                widget: "list"
                field: {label: "Opcja", name: "option", widget: "string"}
              - {label: "Poprawna odpowiedź (1, 2, 3 lub 4)", name: "correct", widget: "number"}
      - label: "Opisy"
        name: "opisy"
        file: "data/bhp_opisy.json"
        fields:
          - label: "Lista Opisów"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", required: false}
              - {label: "Tytuł / Pytanie", name: "question", widget: "string"}
              - {label: "Opis / Odpowiedź", name: "answer", widget: "text"}
              - {label: "Zdjęcie (opcjonalnie)", name: "image", widget: "image", required: false}
      - label: "Ustawienia Egzaminu"
        name: "ustawienia"
        file: "data/bhp_ustawienia.json"
        fields:
          - label: "Reguły losowania pytań na egzamin"
            name: "rules"
            widget: "list"
            required: false
            fields:
              - {label: "Ile pytań wylosować z tego zakresu?", name: "count", widget: "number"}
              - {label: "Od ID", name: "min", widget: "number"}
              - {label: "Do ID", name: "max", widget: "number"}
